# home-assistant locally via docker compose


services:

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
      - "TZ=PDT"
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    logging:
      driver: ${LOGGING_HOME_ASSISTANT:-json-file}
    expose:
      - "${PORT_HOME_ASSISTANT:-8123}"

  websocket-relay:
    build:
      context: websocket-relay
    restart: unless-stopped
    network_mode: host
    environment:
      - "PORT_HOME_ASSISTANT=${PORT_HOME_ASSISTANT:-8123}"
    volumes:
      - ./websocket-relay/index.js:/repo/index.js
      - ./websocket-relay/justfile:/repo/justfile
    logging:
      driver: ${LOGGING_WEBSOCKET_RELAY:-json-file}
